//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/07/2017 at 15:17:18
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :lib_mw
// Cell Name    :b13
// Hierarchy delimiter:'/'
//


module b13 (reset , data_in_2_ , data_in_3_ , data_in_4_ , data_in_5_ , 
    data_in_6_ , data_in_7_ , clock , eoc , add_mpx2 , load_dato , soc , 
    Scan_In , Scan_Enable , dsr , data_in_0_ , data_in_1_ , Scan_Out , 
    data_out , error , mux_en , canale_0_ , canale_1_ , canale_2_ , 
    canale_3_ );
input  reset ;
input  data_in_2_ ;
input  data_in_3_ ;
input  data_in_4_ ;
input  data_in_5_ ;
input  data_in_6_ ;
input  data_in_7_ ;
input  clock ;
input  eoc ;
output add_mpx2 ;
output load_dato ;
output soc ;
input  Scan_In ;
input  Scan_Enable ;
input  dsr ;
input  data_in_0_ ;
input  data_in_1_ ;
output Scan_Out ;
output data_out ;
output error ;
output mux_en ;
output canale_0_ ;
output canale_1_ ;
output canale_2_ ;
output canale_3_ ;



NBUFFX2 CBUFNBUFFX2_G1B1I4_1 (.IN ( clock ) , .Q ( clock_G1B1I4_1 ) ) ;
NBUFFX2 CBUFNBUFFX2_G1B1I3_1 (.IN ( clock ) , .Q ( clock_G1B1I3_1 ) ) ;
NBUFFX2 CBUFNBUFFX2_G1B1I2_1 (.IN ( clock ) , .Q ( clock_G1B1I2_1 ) ) ;
NBUFFX2 CBUFNBUFFX2_G1B1I1_1 (.IN ( clock ) , .Q ( clock_G1B1I1_1 ) ) ;
INVX0 u02a_iopt2 (.QN ( canale_3_ ) , .IN ( n14 ) ) ;
TIEH u02a_iopt1 (.Z ( n14 ) ) ;
SDFFARX1 tx_conta_reg_3_0 (.QN ( n384 ) , .Q ( n339 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n844 ) , .D ( n266 ) ) ;
SDFFARX1 next_bit_reg_1_0 (.QN ( n880 ) , .Q ( n819 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n397 ) , .D ( n268 ) ) ;
SDFFARX1 tx_conta_reg_2_0 (.QN ( n992 ) , .Q ( n844 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( tx_conta_1_N ) , .D ( n262 ) ) ;
SDFFARX1 tx_conta_reg_4_0 (.QN ( n831 ) , .Q ( tx_conta_4_N ) 
    , .CLK ( clock_G1B1I4_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n339 ) 
    , .D ( n267 ) ) ;
SDFFARX1 tx_conta_reg_5_0 (.QN ( n891 ) , .Q ( tx_conta_5_N ) 
    , .CLK ( clock_G1B1I4_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) 
    , .SI ( tx_conta_4_N ) , .D ( n261 ) ) ;
SDFFARX1 tx_conta_reg_0_0 (.QN ( n751 ) , .Q ( n_62 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( tre ) , .D ( n257 ) ) ;
SDFFARX1 next_bit_reg_0_0 (.QN ( n894 ) , .Q ( n397 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( mux_en ) , .D ( n264 ) ) ;
SDFFARX1 rdy_reg (.QN ( n892 ) , .Q ( n358 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_22 ) , .D ( n245 ) ) ;
SDFFARX1 conta_tmp_reg_1_0 (.Q ( n370 ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n396 ) , .D ( n253 ) ) ;
SDFFARX1 conta_tmp_reg_2_0 (.QN ( n890 ) , .Q ( n_260 ) 
    , .CLK ( clock_G1B1I1_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n370 ) 
    , .D ( n252 ) ) ;
SDFFARX1 shot_reg (.QN ( n823 ) , .Q ( shot ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n379 ) , .D ( n239 ) ) ;
SDFFARX1 S2_reg_0_0 (.QN ( n371 ) , .Q ( n330 ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( S1_2_N ) , .D ( n232 ) ) ;
SDFFARX1 mpx_reg (.QN ( n402 ) , .Q ( mpx ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( load ) , .D ( n240 ) ) ;
SDFFARX1 itfc_state_reg_1_0 (.QN ( n889 ) , .Q ( n400 ) 
    , .CLK ( clock_G1B1I1_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n543 ) 
    , .D ( n233 ) ) ;
SDFFARX1 S1_reg_1_0 (.QN ( n757 ) , .Q ( S1_1_N ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n821 ) , .D ( n246 ) ) ;
SDFFARX1 confirm_reg (.QN ( n403 ) , .Q ( confirm ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( canale_2_ ) , .D ( n236 ) ) ;
SDFFARX1 send_en_reg (.QN ( n887 ) , .Q ( send_en ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( send_data ) , .D ( n229 ) ) ;
SDFFARX1 itfc_state_reg_0_0 (.QN ( n893 ) , .Q ( n543 ) 
    , .CLK ( clock_G1B1I1_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( error ) 
    , .D ( n235 ) ) ;
SDFFARX1 S1_reg_0_0 (.QN ( n872 ) , .Q ( n821 ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( Scan_In ) , .D ( n247 ) ) ;
SDFFARX1 tre_reg (.Q ( tre ) , .CLK ( clock_G1B1I3_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( soc ) , .D ( n221 ) ) ;
SDFFARX1 S1_reg_2_0 (.QN ( n755 ) , .Q ( S1_2_N ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( S1_1_N ) , .D ( n242 ) ) ;
SDFFARX1 load_reg (.QN ( n754 ) , .Q ( load ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( load_dato ) , .D ( n238 ) ) ;
SDFFARX1 out_reg_reg_3_0 (.Q ( out_reg_18 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_17 ) , .D ( n226 ) ) ;
SDFFARX1 out_reg_reg_5_0 (.Q ( out_reg_20 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_19 ) , .D ( n230 ) ) ;
SDFFARX1 send_data_reg (.Q ( send_data ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n358 ) , .D ( n243 ) ) ;
SDFFARX1 S2_reg_1_0 (.Q ( n372 ) , .CLK ( clock_G1B1I3_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( n330 ) , .D ( n234 ) ) ;
SDFFARX1 out_reg_reg_0_0 (.Q ( out_reg ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( next_bit_26 ) , .D ( n225 ) ) ;
SDFFARX1 out_reg_reg_2_0 (.Q ( out_reg_17 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_16 ) , .D ( n224 ) ) ;
NAND2X0 U743 (.IN1 ( n992 ) , .QN ( n955 ) , .IN2 ( n751 ) ) ;
NOR2X0 U679 (.IN2 ( n955 ) , .QN ( n956 ) , .IN1 ( tx_conta_1_N ) ) ;
NAND2X0 U631 (.QN ( n984 ) , .IN2 ( tx_conta_5_N ) , .IN1 ( tx_conta_6_N ) ) ;
NOR2X0 U804 (.IN1 ( n957 ) , .QN ( n959 ) , .IN2 ( n984 ) ) ;
OR2X1 U748 (.IN2 ( n887 ) , .IN1 ( n959 ) , .Q ( n1007 ) ) ;
NAND2X0 U799 (.IN1 ( n392 ) , .QN ( n972 ) , .IN2 ( out_reg_17 ) ) ;
NAND2X0 U800 (.IN1 ( n392 ) , .QN ( n967 ) , .IN2 ( out_reg_18 ) ) ;
NAND2X0 U660 (.IN1 ( n9 ) , .QN ( n966 ) , .IN2 ( out_reg_22 ) ) ;
NOR2X0 U672 (.IN2 ( out_reg_19 ) , .QN ( n973 ) , .IN1 ( n9 ) ) ;
NOR2X0 U734 (.IN1 ( n9 ) , .QN ( n1019 ) , .IN2 ( n819 ) ) ;
INVX0 U749 (.IN ( n1007 ) , .QN ( n863 ) ) ;
NAND2X0 U662 (.IN1 ( n972 ) , .QN ( n975 ) , .IN2 ( n819 ) ) ;
NAND2X0 U694 (.IN1 ( n967 ) , .QN ( n968 ) , .IN2 ( n966 ) ) ;
NAND2X0 U700 (.IN1 ( n973 ) , .QN ( n974 ) , .IN2 ( n880 ) ) ;
AND2X1 U524 (.IN1 ( n_62 ) , .Q ( n989 ) , .IN2 ( tx_conta_1_N ) ) ;
NAND2X0 U722 (.IN1 ( n894 ) , .QN ( n962 ) , .IN2 ( out_reg_16 ) ) ;
NAND2X0 U737 (.IN1 ( n1019 ) , .QN ( n970 ) , .IN2 ( out_reg_20 ) ) ;
NAND2X0 U747 (.IN1 ( n397 ) , .QN ( n961 ) , .IN2 ( out_reg ) ) ;
NAND2X0 U753 (.QN ( n991 ) , .IN2 ( n863 ) , .IN1 ( n751 ) ) ;
NAND2X0 U771 (.QN ( n1002 ) , .IN2 ( n989 ) , .IN1 ( n844 ) ) ;
AND2X1 U630 (.IN1 ( n959 ) , .Q ( n1015 ) , .IN2 ( send_en ) ) ;
NAND2X0 U661 (.IN1 ( out_reg_21 ) , .QN ( n977 ) , .IN2 ( n9 ) ) ;
NAND2X0 U693 (.IN1 ( n819 ) , .QN ( n969 ) , .IN2 ( n968 ) ) ;
NAND2X0 U702 (.IN1 ( n975 ) , .QN ( n976 ) , .IN2 ( n974 ) ) ;
NOR2X0 U726 (.IN2 ( next_bit_26 ) , .QN ( n1014 ) , .IN1 ( n392 ) ) ;
NOR2X0 U782 (.IN1 ( tx_conta_1_N ) , .QN ( n996 ) , .IN2 ( n1007 ) ) ;
NAND2X0 U789 (.QN ( n995 ) , .IN2 ( n991 ) , .IN1 ( send_en ) ) ;
AND2X1 U790 (.Q ( n986 ) , .IN1 ( tx_conta_4_N ) , .IN2 ( send_en ) ) ;
NAND2X0 U654 (.IN1 ( n962 ) , .QN ( n963 ) , .IN2 ( n961 ) ) ;
NAND2X0 U681 (.IN1 ( n970 ) , .QN ( n971 ) , .IN2 ( n969 ) ) ;
NAND2X0 U703 (.IN1 ( n977 ) , .QN ( n978 ) , .IN2 ( n976 ) ) ;
INVX0 U608 (.IN ( n1015 ) , .QN ( n835 ) ) ;
AND2X1 U724 (.IN1 ( n6 ) , .Q ( n987 ) , .IN2 ( n986 ) ) ;
NAND2X0 U725 (.IN1 ( n963 ) , .QN ( n964 ) , .IN2 ( next_bit_26 ) ) ;
NOR2X0 U735 (.IN1 ( eoc ) , .QN ( n929 ) , .IN2 ( S1_1_N ) ) ;
NAND2X0 U754 (.IN1 ( n863 ) , .QN ( n1008 ) , .IN2 ( n6 ) ) ;
NAND2X0 U755 (.QN ( n1004 ) , .IN2 ( n992 ) , .IN1 ( n863 ) ) ;
NOR2X0 U756 (.IN1 ( n757 ) , .QN ( n931 ) , .IN2 ( n892 ) ) ;
NAND2X0 U765 (.IN1 ( n894 ) , .QN ( n998 ) , .IN2 ( n5 ) ) ;
NAND2X0 U768 (.QN ( n911 ) , .IN2 ( n332 ) , .IN1 ( n543 ) ) ;
NAND2X0 U772 (.QN ( n902 ) , .IN2 ( dsr ) , .IN1 ( tre ) ) ;
NOR2X0 U795 (.IN2 ( n890 ) , .QN ( n943 ) , .IN1 ( n7 ) ) ;
NOR2X0 U803 (.IN1 ( n996 ) , .QN ( n1005 ) , .IN2 ( n995 ) ) ;
NAND2X0 U805 (.IN1 ( n8 ) , .QN ( n952 ) , .IN2 ( S1_2_N ) ) ;
AND2X1 U633 (.IN1 ( confirm ) , .Q ( n920 ) , .IN2 ( n917 ) ) ;
NAND2X0 U663 (.IN1 ( S1_1_N ) , .QN ( n933 ) , .IN2 ( n892 ) ) ;
NOR2X0 U678 (.IN2 ( load ) , .QN ( n900 ) , .IN1 ( error ) ) ;
NAND2X0 U680 (.IN1 ( n971 ) , .QN ( n980 ) , .IN2 ( n894 ) ) ;
NOR2X0 U706 (.IN2 ( n754 ) , .QN ( n905 ) , .IN1 ( tre ) ) ;
NAND2X0 U709 (.IN1 ( n978 ) , .QN ( n979 ) , .IN2 ( n397 ) ) ;
NAND2X0 U712 (.IN1 ( n757 ) , .QN ( n934 ) , .IN2 ( eoc ) ) ;
NOR2X0 U530 (.IN2 ( n396 ) , .QN ( n939 ) , .IN1 ( n370 ) ) ;
NAND2X0 U551 (.IN1 ( n1014 ) , .QN ( n1016 ) , .IN2 ( n894 ) ) ;
NAND2X0 U614 (.QN ( n1009 ) , .IN2 ( n984 ) , .IN1 ( n986 ) ) ;
NAND2X0 U718 (.IN1 ( n920 ) , .QN ( n926 ) , .IN2 ( mpx ) ) ;
NOR2X0 U723 (.IN2 ( n987 ) , .QN ( n988 ) , .IN1 ( n891 ) ) ;
NAND2X0 U729 (.IN1 ( n998 ) , .QN ( n999 ) , .IN2 ( n888 ) ) ;
NAND2X0 U732 (.IN1 ( shot ) , .QN ( n915 ) , .IN2 ( n889 ) ) ;
NAND2X0 U741 (.IN1 ( n371 ) , .QN ( n906 ) , .IN2 ( send_data ) ) ;
NOR2X0 U757 (.IN2 ( n1009 ) , .QN ( n985 ) , .IN1 ( n891 ) ) ;
NAND2X0 U774 (.QN ( n878 ) , .IN2 ( n917 ) , .IN1 ( confirm ) ) ;
NAND2X0 U780 (.QN ( n938 ) , .IN2 ( n929 ) , .IN1 ( n11 ) ) ;
NOR2X0 U784 (.IN2 ( n952 ) , .QN ( n946 ) , .IN1 ( n943 ) ) ;
NAND2X0 U796 (.IN1 ( n7 ) , .QN ( n945 ) , .IN2 ( n890 ) ) ;
NAND2X0 U802 (.QN ( n1012 ) , .IN2 ( n1004 ) , .IN1 ( n1005 ) ) ;
NAND2X0 U655 (.IN1 ( n931 ) , .QN ( n923 ) , .IN2 ( n821 ) ) ;
NAND2X0 U658 (.IN1 ( S1_2_N ) , .QN ( n930 ) , .IN2 ( n821 ) ) ;
NAND2X0 U666 (.QN ( n1000 ) , .IN2 ( n819 ) , .IN1 ( n10 ) ) ;
INVX0 U668 (.IN ( n1004 ) , .QN ( n990 ) ) ;
INVX0 U669 (.IN ( n902 ) , .QN ( n903 ) ) ;
NOR2X0 U671 (.IN2 ( S1_1_N ) , .QN ( n937 ) , .IN1 ( S1_2_N ) ) ;
NOR2X0 U673 (.IN2 ( n1002 ) , .QN ( n1003 ) , .IN1 ( n339 ) ) ;
NOR2X0 U676 (.IN2 ( n880 ) , .QN ( n1018 ) , .IN1 ( n10 ) ) ;
NOR2X0 U677 (.IN2 ( n379 ) , .QN ( n901 ) , .IN1 ( n900 ) ) ;
NAND2X0 U683 (.IN1 ( n911 ) , .QN ( n912 ) , .IN2 ( n403 ) ) ;
NAND2X0 U685 (.IN1 ( n400 ) , .QN ( n913 ) , .IN2 ( n893 ) ) ;
NOR2X0 U689 (.IN2 ( n835 ) , .QN ( n1017 ) , .IN1 ( n1016 ) ) ;
NAND2X0 U690 (.IN1 ( n402 ) , .QN ( n907 ) , .IN2 ( confirm ) ) ;
NOR2X0 U701 (.IN2 ( n872 ) , .QN ( n932 ) , .IN1 ( n931 ) ) ;
NAND2X0 U708 (.IN1 ( n980 ) , .QN ( n981 ) , .IN2 ( n979 ) ) ;
NOR2X0 U529 (.IN2 ( n952 ) , .QN ( n940 ) , .IN1 ( n939 ) ) ;
NOR2X0 U531 (.IN2 ( n5 ) , .QN ( n965 ) , .IN1 ( n964 ) ) ;
NOR2X0 U613 (.IN2 ( n1009 ) , .QN ( n1010 ) , .IN1 ( n339 ) ) ;
NOR2X0 U523 (.IN2 ( tx_conta_4_N ) , .QN ( n1011 ) , .IN1 ( n1008 ) ) ;
OR2X1 U716 (.IN2 ( n396 ) , .IN1 ( n952 ) , .Q ( n950 ) ) ;
OR2X1 U720 (.IN2 ( n906 ) , .IN1 ( n372 ) , .Q ( n927 ) ) ;
NAND2X0 U730 (.IN1 ( n10 ) , .QN ( n960 ) , .IN2 ( n888 ) ) ;
NAND2X0 U731 (.IN1 ( n981 ) , .QN ( n982 ) , .IN2 ( n888 ) ) ;
NAND2X0 U733 (.IN1 ( shot ) , .QN ( n910 ) , .IN2 ( n893 ) ) ;
NAND2X0 U736 (.IN1 ( n10 ) , .QN ( n1020 ) , .IN2 ( n1019 ) ) ;
OR2X1 U742 (.IN2 ( n992 ) , .IN1 ( n1005 ) , .Q ( n993 ) ) ;
NAND2X0 U752 (.QN ( n922 ) , .IN2 ( n920 ) , .IN1 ( n402 ) ) ;
NAND2X0 U760 (.QN ( n909 ) , .IN2 ( n911 ) , .IN1 ( n400 ) ) ;
NAND2X0 U763 (.QN ( n953 ) , .IN2 ( n945 ) , .IN1 ( n946 ) ) ;
NAND2X0 U778 (.IN1 ( mpx ) , .QN ( n921 ) , .IN2 ( n878 ) ) ;
NAND2X0 U785 (.IN1 ( n952 ) , .QN ( n949 ) , .IN2 ( n370 ) ) ;
NAND2X0 U786 (.IN1 ( canale_2_ ) , .QN ( n954 ) , .IN2 ( n952 ) ) ;
NAND2X0 U787 (.IN1 ( load_dato ) , .QN ( n925 ) , .IN2 ( n952 ) ) ;
NAND2X0 U794 (.QN ( n948 ) , .IN2 ( n7 ) , .IN1 ( n940 ) ) ;
NOR2X0 U806 (.IN2 ( n888 ) , .QN ( n1023 ) , .IN1 ( n10 ) ) ;
NOR2X0 U807 (.IN1 ( n9 ) , .QN ( n1024 ) , .IN2 ( n1000 ) ) ;
NAND2X0 U656 (.IN1 ( n_260 ) , .QN ( n947 ) , .IN2 ( n952 ) ) ;
NAND2X0 U657 (.IN1 ( n926 ) , .QN ( n928 ) , .IN2 ( n358 ) ) ;
NAND2X0 U664 (.IN1 ( canale_0_ ) , .QN ( n942 ) , .IN2 ( n952 ) ) ;
NAND2X0 U665 (.IN1 ( n396 ) , .QN ( n951 ) , .IN2 ( n952 ) ) ;
NAND2X0 U667 (.IN1 ( n990 ) , .QN ( n994 ) , .IN2 ( n989 ) ) ;
NOR2X0 U674 (.IN2 ( n835 ) , .QN ( n983 ) , .IN1 ( n965 ) ) ;
NOR2X0 U675 (.IN2 ( n1017 ) , .QN ( n1021 ) , .IN1 ( n1018 ) ) ;
NAND2X0 U684 (.IN1 ( n913 ) , .QN ( n914 ) , .IN2 ( n379 ) ) ;
NAND2X0 U692 (.IN1 ( n_62 ) , .QN ( n958 ) , .IN2 ( n887 ) ) ;
NAND2X0 U695 (.IN1 ( n907 ) , .QN ( n908 ) , .IN2 ( n917 ) ) ;
NAND2X0 U705 (.IN1 ( n915 ) , .QN ( n916 ) , .IN2 ( n754 ) ) ;
OR2X1 U528 (.IN2 ( n371 ) , .IN1 ( n372 ) , .Q ( n918 ) ) ;
NOR2X0 U576 (.IN2 ( n332 ) , .QN ( n899 ) , .IN1 ( tre ) ) ;
NAND2X0 U606 (.IN1 ( n952 ) , .QN ( n941 ) , .IN2 ( canale_1_ ) ) ;
INVX0 U612 (.IN ( n808 ) , .QN ( data_out ) ) ;
INVX2 X02_place1 (.IN ( reset ) , .QN ( n3 ) ) ;
NAND2X0 U715 (.IN1 ( n942 ) , .QN ( n251 ) , .IN2 ( n950 ) ) ;
NAND2X0 U719 (.IN1 ( n928 ) , .QN ( n245 ) , .IN2 ( n927 ) ) ;
NAND2X0 U727 (.IN1 ( n994 ) , .QN ( n262 ) , .IN2 ( n993 ) ) ;
NAND2X0 U750 (.IN1 ( n921 ) , .QN ( n240 ) , .IN2 ( n922 ) ) ;
NAND2X0 U751 (.IN1 ( n756 ) , .QN ( n241 ) , .IN2 ( n922 ) ) ;
NAND2X0 U758 (.IN1 ( n910 ) , .QN ( n235 ) , .IN2 ( n909 ) ) ;
NAND2X0 U759 (.IN1 ( n12 ) , .QN ( n233 ) , .IN2 ( n909 ) ) ;
NAND2X0 U761 (.IN1 ( n947 ) , .QN ( n252 ) , .IN2 ( n953 ) ) ;
NAND2X0 U762 (.IN1 ( n954 ) , .QN ( n256 ) , .IN2 ( n953 ) ) ;
NAND2X0 U776 (.IN1 ( n914 ) , .QN ( n237 ) , .IN2 ( n12 ) ) ;
NAND2X0 U777 (.IN1 ( n878 ) , .QN ( n232 ) , .IN2 ( n927 ) ) ;
OR2X1 U632 (.IN2 ( n1023 ) , .IN1 ( n1024 ) , .Q ( n269 ) ) ;
NOR2X0 U670 (.IN2 ( n1024 ) , .QN ( n265 ) , .IN1 ( n1001 ) ) ;
NAND2X0 U682 (.IN1 ( n949 ) , .QN ( n253 ) , .IN2 ( n948 ) ) ;
NAND2X0 U686 (.IN1 ( n941 ) , .QN ( n250 ) , .IN2 ( n948 ) ) ;
NAND2X0 U687 (.IN1 ( n925 ) , .QN ( n244 ) , .IN2 ( n938 ) ) ;
NAND2X0 U688 (.IN1 ( n919 ) , .QN ( n239 ) , .IN2 ( n918 ) ) ;
NAND2X0 U691 (.IN1 ( n983 ) , .QN ( n259 ) , .IN2 ( n982 ) ) ;
NAND2X0 U696 (.IN1 ( n958 ) , .QN ( n257 ) , .IN2 ( n991 ) ) ;
NAND2X0 U697 (.IN1 ( n908 ) , .QN ( n234 ) , .IN2 ( n918 ) ) ;
NAND2X0 U698 (.IN1 ( n821 ) , .QN ( n247 ) , .IN2 ( n935 ) ) ;
NAND2X0 U699 (.IN1 ( n1021 ) , .QN ( n268 ) , .IN2 ( n1020 ) ) ;
NAND2X0 U707 (.IN1 ( n754 ) , .QN ( n221 ) , .IN2 ( n899 ) ) ;
NAND2X0 U714 (.IN1 ( n951 ) , .QN ( n254 ) , .IN2 ( n950 ) ) ;
NOR2X0 U552 (.IN2 ( n960 ) , .QN ( n258 ) , .IN1 ( n5 ) ) ;
NAND2X0 X02_place9 (.IN1 ( n543 ) , .IN2 ( n889 ) , .QN ( n12 ) ) ;
NOR2X0 X02_place8 (.QN ( n11 ) , .IN1 ( n755 ) , .IN2 ( n872 ) ) ;
NOR2X0 X02_place7 (.QN ( n10 ) , .IN1 ( n835 ) , .IN2 ( n894 ) ) ;
NOR2X0 X02_place6 (.QN ( n8 ) , .IN1 ( n757 ) , .IN2 ( n821 ) ) ;
NAND2X0 X02_place5 (.IN1 ( n396 ) , .IN2 ( n370 ) , .QN ( n7 ) ) ;
NOR2X0 X02_place4 (.QN ( n6 ) , .IN1 ( n384 ) , .IN2 ( n1002 ) ) ;
NAND2X0 X02_place3 (.IN1 ( n9 ) , .IN2 ( n880 ) , .QN ( n5 ) ) ;
AND2X1 U779 (.Q ( n917 ) , .IN1 ( n372 ) , .IN2 ( n371 ) ) ;
INVX0 X02_place2 (.QN ( n4 ) , .IN ( n905 ) ) ;
OR2X1 U532 (.IN2 ( n764 ) , .IN1 ( n763 ) , .Q ( n228 ) ) ;
AND2X1 U533 (.IN1 ( n4 ) , .IN2 ( out_reg_21 ) , .Q ( n763 ) ) ;
AND2X1 U534 (.IN1 ( n905 ) , .IN2 ( data_in_6_ ) , .Q ( n764 ) ) ;
OR2X1 U535 (.IN2 ( n766 ) , .IN1 ( n765 ) , .Q ( n231 ) ) ;
AND2X1 U536 (.IN1 ( n4 ) , .IN2 ( out_reg_22 ) , .Q ( n765 ) ) ;
AND2X1 U537 (.IN1 ( n905 ) , .IN2 ( data_in_7_ ) , .Q ( n766 ) ) ;
OR2X1 U538 (.IN2 ( n768 ) , .IN1 ( n767 ) , .Q ( n227 ) ) ;
AND2X1 U539 (.IN1 ( n4 ) , .IN2 ( out_reg_16 ) , .Q ( n767 ) ) ;
AND2X1 U540 (.IN1 ( n905 ) , .IN2 ( data_in_1_ ) , .Q ( n768 ) ) ;
OR2X1 U541 (.IN2 ( n770 ) , .IN1 ( n769 ) , .Q ( n263 ) ) ;
AND2X1 U542 (.IN1 ( tx_conta_1_N ) , .IN2 ( n995 ) , .Q ( n769 ) ) ;
AND2X1 U543 (.IN1 ( n996 ) , .IN2 ( n_62 ) , .Q ( n770 ) ) ;
OR2X1 U544 (.IN2 ( n772 ) , .IN1 ( n771 ) , .Q ( n266 ) ) ;
AND2X1 U545 (.IN1 ( n1003 ) , .IN2 ( n863 ) , .Q ( n771 ) ) ;
AND2X1 U546 (.IN1 ( n339 ) , .IN2 ( n1012 ) , .Q ( n772 ) ) ;
OR2X1 U547 (.IN2 ( n774 ) , .IN1 ( n773 ) , .Q ( n267 ) ) ;
OR2X1 U548 (.IN2 ( n1010 ) , .IN1 ( n1011 ) , .Q ( n773 ) ) ;
AND2X1 U549 (.IN1 ( n1012 ) , .IN2 ( tx_conta_4_N ) , .Q ( n774 ) ) ;
AND2X1 U550 (.IN1 ( n1000 ) , .IN2 ( n9 ) , .Q ( n1001 ) ) ;
OR2X1 U553 (.IN2 ( n776 ) , .IN1 ( n775 ) , .Q ( n264 ) ) ;
AND2X1 U554 (.IN1 ( n835 ) , .IN2 ( n397 ) , .Q ( n775 ) ) ;
AND2X1 U555 (.IN1 ( n999 ) , .IN2 ( n1015 ) , .Q ( n776 ) ) ;
OR2X1 U556 (.IN2 ( n778 ) , .IN1 ( n777 ) , .Q ( n261 ) ) ;
AND2X1 U557 (.IN1 ( n891 ) , .IN2 ( n987 ) , .Q ( n777 ) ) ;
AND2X1 U558 (.IN1 ( n835 ) , .IN2 ( n988 ) , .Q ( n778 ) ) ;
OR2X1 U559 (.IN2 ( n823 ) , .IN1 ( n779 ) , .Q ( n919 ) ) ;
AND2X1 U560 (.IN1 ( n917 ) , .IN2 ( n403 ) , .Q ( n779 ) ) ;
OR2X1 U561 (.IN2 ( n781 ) , .IN1 ( n780 ) , .Q ( n236 ) ) ;
AND2X1 U562 (.IN1 ( n912 ) , .IN2 ( n400 ) , .Q ( n780 ) ) ;
AND2X1 U563 (.IN1 ( confirm ) , .IN2 ( n543 ) , .Q ( n781 ) ) ;
AND2X1 U564 (.IN1 ( n782 ) , .IN2 ( n783 ) , .Q ( n246 ) ) ;
OR2X1 U565 (.IN2 ( n929 ) , .IN1 ( n930 ) , .Q ( n782 ) ) ;
OR2X1 U566 (.IN2 ( n932 ) , .IN1 ( S1_2_N ) , .Q ( n783 ) ) ;
OR2X1 U567 (.IN2 ( n785 ) , .IN1 ( n784 ) , .Q ( n935 ) ) ;
AND2X1 U568 (.IN1 ( n933 ) , .IN2 ( n755 ) , .Q ( n784 ) ) ;
AND2X1 U569 (.IN1 ( S1_2_N ) , .IN2 ( n934 ) , .Q ( n785 ) ) ;
OR2X1 U570 (.IN2 ( n787 ) , .IN1 ( n786 ) , .Q ( n229 ) ) ;
AND2X1 U571 (.IN1 ( n903 ) , .IN2 ( n379 ) , .Q ( n786 ) ) ;
AND2X1 U572 (.IN1 ( n355 ) , .IN2 ( send_en ) , .Q ( n787 ) ) ;
AND2X1 U573 (.IN1 ( n12 ) , .IN2 ( n916 ) , .Q ( n238 ) ) ;
OR2X1 U575 (.IN2 ( n11 ) , .IN1 ( n8 ) , .Q ( n242 ) ) ;
OR2X1 U577 (.IN2 ( n789 ) , .IN1 ( n788 ) , .Q ( n243 ) ) ;
AND2X1 U578 (.IN1 ( n11 ) , .IN2 ( S1_1_N ) , .Q ( n788 ) ) ;
AND2X1 U579 (.IN1 ( n923 ) , .IN2 ( send_data ) , .Q ( n789 ) ) ;
AND2X1 U580 (.IN1 ( n790 ) , .IN2 ( n952 ) , .Q ( n248 ) ) ;
OR2X1 U581 (.IN2 ( soc ) , .IN1 ( n8 ) , .Q ( n790 ) ) ;
OR2X1 U582 (.IN2 ( n792 ) , .IN1 ( n791 ) , .Q ( n223 ) ) ;
AND2X1 U583 (.IN1 ( n4 ) , .IN2 ( out_reg_19 ) , .Q ( n791 ) ) ;
AND2X1 U584 (.IN1 ( n905 ) , .IN2 ( data_in_4_ ) , .Q ( n792 ) ) ;
OR2X1 U585 (.IN2 ( n794 ) , .IN1 ( n793 ) , .Q ( n230 ) ) ;
AND2X1 U586 (.IN1 ( n4 ) , .IN2 ( out_reg_20 ) , .Q ( n793 ) ) ;
AND2X1 U587 (.IN1 ( n905 ) , .IN2 ( data_in_5_ ) , .Q ( n794 ) ) ;
OR2X1 U588 (.IN2 ( n796 ) , .IN1 ( n795 ) , .Q ( n226 ) ) ;
AND2X1 U589 (.IN1 ( n4 ) , .IN2 ( out_reg_18 ) , .Q ( n795 ) ) ;
AND2X1 U590 (.IN1 ( n905 ) , .IN2 ( data_in_3_ ) , .Q ( n796 ) ) ;
OR2X1 U591 (.IN2 ( n798 ) , .IN1 ( n797 ) , .Q ( n224 ) ) ;
AND2X1 U592 (.IN1 ( n4 ) , .IN2 ( out_reg_17 ) , .Q ( n797 ) ) ;
AND2X1 U593 (.IN1 ( n905 ) , .IN2 ( data_in_2_ ) , .Q ( n798 ) ) ;
OR2X1 U594 (.IN2 ( n800 ) , .IN1 ( n799 ) , .Q ( n225 ) ) ;
AND2X1 U595 (.IN1 ( n4 ) , .IN2 ( out_reg ) , .Q ( n799 ) ) ;
AND2X1 U596 (.IN1 ( n905 ) , .IN2 ( data_in_0_ ) , .Q ( n800 ) ) ;
OR2X1 U597 (.IN2 ( n802 ) , .IN1 ( n801 ) , .Q ( n249 ) ) ;
AND2X1 U598 (.IN1 ( n937 ) , .IN2 ( n872 ) , .Q ( n801 ) ) ;
AND2X1 U599 (.IN1 ( mux_en ) , .IN2 ( n938 ) , .Q ( n802 ) ) ;
OR2X1 U600 (.IN2 ( n804 ) , .IN1 ( n803 ) , .Q ( n260 ) ) ;
AND2X1 U601 (.IN1 ( n6 ) , .IN2 ( n985 ) , .Q ( n803 ) ) ;
AND2X1 U602 (.IN1 ( tx_conta_6_N ) , .IN2 ( n835 ) , .Q ( n804 ) ) ;
OR2X1 U603 (.IN2 ( n806 ) , .IN1 ( n805 ) , .Q ( n222 ) ) ;
AND2X1 U604 (.IN1 ( n379 ) , .IN2 ( n902 ) , .Q ( n805 ) ) ;
AND2X1 U605 (.IN1 ( n901 ) , .IN2 ( n4 ) , .Q ( n806 ) ) ;
SDFFARX1 canale_reg_1_0 (.Q ( canale_1_ ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( canale_0_ ) , .D ( n250 ) ) ;
SDFFARX1 error_reg (.Q ( error ) , .CLK ( clock_G1B1I1_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( n_260 ) , .D ( n222 ) ) ;
SDFFARX1 send_reg (.Q ( n379 ) , .CLK ( clock_G1B1I1_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( send_en ) , .D ( n237 ) ) ;
SDFFARX1 canale_reg_2_0 (.Q ( canale_2_ ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( canale_1_ ) , .D ( n256 ) ) ;
SDFFARX1 out_reg_reg_4_0 (.Q ( out_reg_19 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_18 ) , .D ( n223 ) ) ;
SDFFARX1 soc_reg (.Q ( soc ) , .CLK ( clock_G1B1I3_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( shot ) , .D ( n248 ) ) ;
SDFFARX1 tx_conta_reg_1_0 (.Q ( tx_conta_1_N ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n_62 ) , .D ( n263 ) ) ;
SDFFARX1 load_dato_reg (.Q ( load_dato ) , .CLK ( clock_G1B1I3_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n400 ) , .D ( n244 ) ) ;
SDFFARX1 out_reg_reg_1_0 (.Q ( out_reg_16 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg ) , .D ( n227 ) ) ;
SDFFARX1 out_reg_reg_7_0 (.Q ( out_reg_22 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_21 ) , .D ( n231 ) ) ;
SDFFARX1 out_reg_reg_6_0 (.Q ( out_reg_21 ) , .CLK ( clock_G1B1I2_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( out_reg_20 ) , .D ( n228 ) ) ;
SDFFARX1 data_out_reg (.QN ( n808 ) , .Q ( Scan_Out ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n332 ) , .D ( n259 ) ) ;
SDFFARX1 canale_reg_0_0 (.Q ( canale_0_ ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( add_mpx2 ) , .D ( n251 ) ) ;
SDFFARX1 tx_conta_reg_6_0 (.Q ( tx_conta_6_N ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( tx_conta_5_N ) , .D ( n260 ) ) ;
SDFFARX1 mux_en_reg (.Q ( mux_en ) , .CLK ( clock_G1B1I2_1 ) , .RSTB ( n3 ) 
    , .SE ( Scan_Enable ) , .SI ( mpx ) , .D ( n249 ) ) ;
SDFFARX1 conta_tmp_reg_0_0 (.Q ( n396 ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( confirm ) , .D ( n254 ) ) ;
SDFFARX1 add_mpx2_reg (.QN ( n756 ) , .Q ( add_mpx2 ) , .CLK ( clock_G1B1I1_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n372 ) , .D ( n241 ) ) ;
SDFFARX1 tx_end_reg (.QN ( n355 ) , .Q ( n332 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( tx_conta_6_N ) , .D ( n258 ) ) ;
SDFFARX1 next_bit_reg_3_0 (.QN ( n888 ) , .Q ( next_bit_26 ) 
    , .CLK ( clock_G1B1I4_1 ) , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n392 ) 
    , .D ( n269 ) ) ;
SDFFARX1 next_bit_reg_2_0 (.QN ( n9 ) , .Q ( n392 ) , .CLK ( clock_G1B1I4_1 ) 
    , .RSTB ( n3 ) , .SE ( Scan_Enable ) , .SI ( n819 ) , .D ( n265 ) ) ;
AND2X1 U520 (.IN1 ( n831 ) , .IN2 ( n762 ) , .Q ( n957 ) ) ;
OR2X1 U521 (.IN2 ( n956 ) , .IN1 ( n384 ) , .Q ( n762 ) ) ;
endmodule


