//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/26/2013 at 19:20:39
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :MW_icc
// Cell Name    :final
// Hierarchy delimiter:'/'
//


module s27 (blif_reset_net , clock , Scan_Out , G17 , Scan_In , 
    Scan_Enable , G3 , G2 , G1 , G0 );
input  blif_reset_net ;
input  clock ;
output Scan_Out ;
output G17 ;
input  Scan_In ;
input  Scan_Enable ;
input  G3 ;
input  G2 ;
input  G1 ;
input  G0 ;



NBUFFX2 CBUF_CTS_clock_CTO_delay42 (.IN ( clock ) 
    , .Q ( CTS_clock_CTO_delay42 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay41 (.IN ( CTS_clock_CTO_delay42 ) 
    , .Q ( CTS_clock_CTO_delay41 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay40 (.IN ( CTS_clock_CTO_delay41 ) 
    , .Q ( CTS_clock_CTO_delay40 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay39 (.IN ( CTS_clock_CTO_delay40 ) 
    , .Q ( CTS_clock_CTO_delay39 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay38 (.IN ( CTS_clock_CTO_delay39 ) 
    , .Q ( CTS_clock_CTO_delay38 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay37 (.IN ( CTS_clock_CTO_delay38 ) 
    , .Q ( CTS_clock_CTO_delay37 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay36 (.IN ( CTS_clock_CTO_delay37 ) 
    , .Q ( CTS_clock_CTO_delay36 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay35 (.IN ( CTS_clock_CTO_delay36 ) 
    , .Q ( CTS_clock_CTO_delay35 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay34 (.IN ( CTS_clock_CTO_delay35 ) 
    , .Q ( CTS_clock_CTO_delay34 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay33 (.IN ( CTS_clock_CTO_delay34 ) 
    , .Q ( CTS_clock_CTO_delay33 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay32 (.IN ( CTS_clock_CTO_delay33 ) 
    , .Q ( CTS_clock_CTO_delay32 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay31 (.IN ( CTS_clock_CTO_delay32 ) 
    , .Q ( CTS_clock_CTO_delay31 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay30 (.IN ( CTS_clock_CTO_delay31 ) 
    , .Q ( CTS_clock_CTO_delay30 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay29 (.IN ( CTS_clock_CTO_delay30 ) 
    , .Q ( CTS_clock_CTO_delay29 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay28 (.IN ( CTS_clock_CTO_delay29 ) 
    , .Q ( CTS_clock_CTO_delay28 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay27 (.IN ( CTS_clock_CTO_delay28 ) 
    , .Q ( CTS_clock_CTO_delay27 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay26 (.IN ( CTS_clock_CTO_delay27 ) 
    , .Q ( CTS_clock_CTO_delay26 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay25 (.IN ( CTS_clock_CTO_delay26 ) 
    , .Q ( CTS_clock_CTO_delay25 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay24 (.IN ( CTS_clock_CTO_delay25 ) 
    , .Q ( CTS_clock_CTO_delay24 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay23 (.IN ( CTS_clock_CTO_delay24 ) 
    , .Q ( CTS_clock_CTO_delay23 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay22 (.IN ( CTS_clock_CTO_delay23 ) 
    , .Q ( CTS_clock_CTO_delay22 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay21 (.IN ( CTS_clock_CTO_delay22 ) 
    , .Q ( CTS_clock_CTO_delay21 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay20 (.IN ( CTS_clock_CTO_delay21 ) 
    , .Q ( CTS_clock_CTO_delay20 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay19 (.IN ( CTS_clock_CTO_delay20 ) 
    , .Q ( CTS_clock_CTO_delay19 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay18 (.IN ( CTS_clock_CTO_delay19 ) 
    , .Q ( CTS_clock_CTO_delay18 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay17 (.IN ( CTS_clock_CTO_delay18 ) 
    , .Q ( CTS_clock_CTO_delay17 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay16 (.IN ( CTS_clock_CTO_delay17 ) 
    , .Q ( CTS_clock_CTO_delay16 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay15 (.IN ( CTS_clock_CTO_delay16 ) 
    , .Q ( CTS_clock_CTO_delay15 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay14 (.IN ( CTS_clock_CTO_delay15 ) 
    , .Q ( CTS_clock_CTO_delay14 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay13 (.IN ( CTS_clock_CTO_delay14 ) 
    , .Q ( CTS_clock_CTO_delay13 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay12 (.IN ( CTS_clock_CTO_delay13 ) 
    , .Q ( CTS_clock_CTO_delay12 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay11 (.IN ( CTS_clock_CTO_delay12 ) 
    , .Q ( CTS_clock_CTO_delay11 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay10 (.IN ( CTS_clock_CTO_delay11 ) 
    , .Q ( CTS_clock_CTO_delay10 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay9 (.IN ( CTS_clock_CTO_delay10 ) 
    , .Q ( CTS_clock_CTO_delay9 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay8 (.IN ( CTS_clock_CTO_delay9 ) 
    , .Q ( CTS_clock_CTO_delay8 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay7 (.IN ( CTS_clock_CTO_delay8 ) 
    , .Q ( CTS_clock_CTO_delay7 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay6 (.IN ( CTS_clock_CTO_delay7 ) 
    , .Q ( CTS_clock_CTO_delay6 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay5 (.IN ( CTS_clock_CTO_delay6 ) 
    , .Q ( CTS_clock_CTO_delay5 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay4 (.IN ( CTS_clock_CTO_delay5 ) 
    , .Q ( CTS_clock_CTO_delay4 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay3 (.IN ( CTS_clock_CTO_delay4 ) 
    , .Q ( CTS_clock_CTO_delay3 ) ) ;
NBUFFX2 CBUF_CTS_clock_CTO_delay2 (.IN ( CTS_clock_CTO_delay3 ) 
    , .Q ( CTS_clock_CTO_delay2 ) ) ;
AND2X2 \02_place1 (.IN1 ( net569 ) , .Q ( n2 ) , .IN2 ( n41 ) ) ;
OAI21X2 \02_place2 (.IN1 ( n40 ) , .QN ( G17 ) , .IN3 ( net380 ) , .IN2 ( n2 ) ) ;
SDFFARX2 G5_reg (.QN ( net380 ) , .Q ( n1 ) , .CLK ( CTS_clock_CTO_delay2 ) 
    , .RSTB ( n33 ) , .SE ( Scan_Enable ) , .SI ( Scan_In ) , .D ( n27 ) ) ;
SDFFARX2 G7_reg (.QN ( net569 ) , .Q ( Scan_Out ) 
    , .CLK ( CTS_clock_CTO_delay2 ) , .RSTB ( n33 ) , .SE ( Scan_Enable ) 
    , .SI ( n30 ) , .D ( G13 ) ) ;
SDFFARX2 G6_reg (.QN ( net565 ) , .Q ( n30 ) , .CLK ( CTS_clock_CTO_delay2 ) 
    , .RSTB ( n33 ) , .SE ( Scan_Enable ) , .SI ( n1 ) , .D ( net416 ) ) ;
NOR2X2 U31 (.IN1 ( net565 ) , .QN ( n40 ) , .IN2 ( G0 ) ) ;
NOR2X2 U32 (.IN1 ( n42 ) , .QN ( n41 ) , .IN2 ( G1 ) ) ;
INVX2 U34 (.QN ( n42 ) , .IN ( G3 ) ) ;
NOR2X2 U35 (.IN1 ( Scan_Out ) , .QN ( net9 ) , .IN2 ( G1 ) ) ;
INVX2 U37 (.IN ( n2 ) , .QN ( net371 ) ) ;
OA21X2 U39 (.Q ( n27 ) , .IN2 ( n1 ) , .IN3 ( G0 ) , .IN1 ( net371 ) ) ;
INVX2 U41 (.QN ( net416 ) , .IN ( G17 ) ) ;
NOR2X2 U42 (.IN1 ( net9 ) , .QN ( G13 ) , .IN2 ( G2 ) ) ;
INVX2 U43 (.IN ( blif_reset_net ) , .QN ( n33 ) ) ;
endmodule


