//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/26/2013 at 19:20:39
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :MW_icc
// Cell Name    :final
// Hierarchy delimiter:'/'
//


module s27 (blif_reset_net , clock , Scan_Out , G17 , Scan_In , 
    Scan_Enable , G3 , G2 , G1 , G0 );
input  blif_reset_net ;
input  clock ;
output Scan_Out ;
output G17 ;
input  Scan_In ;
input  Scan_Enable ;
input  G3 ;
input  G2 ;
input  G1 ;
input  G0 ;

AND2X2 \02_place1 (.IN1 ( net569 ) , .Q ( n2 ) , .IN2 ( n41 ) ) ;
OAI21X2 \02_place2 (.IN1 ( n40 ) , .QN ( G17 ) , .IN3 ( net380 ) , .IN2 ( n2 ) ) ;
SDFFARX2 G5_reg (.QN ( net380 ) , .Q ( n1 ) , .CLK ( clock ) 
    , .RSTB ( n33 ) , .SE ( Scan_Enable ) , .SI ( Scan_In ) , .D ( n27 ) ) ;
SDFFARX2 G7_reg (.QN ( net569 ) , .Q ( Scan_Out ) 
    , .CLK ( clock ) , .RSTB ( n33 ) , .SE ( Scan_Enable ) 
    , .SI ( n30 ) , .D ( G13 ) ) ;
SDFFARX2 G6_reg (.QN ( net565 ) , .Q ( n30 ) , .CLK ( clock ) 
    , .RSTB ( n33 ) , .SE ( Scan_Enable ) , .SI ( n1 ) , .D ( net416 ) ) ;
NOR2X2 U31 (.IN1 ( net565 ) , .QN ( n40 ) , .IN2 ( G0 ) ) ;
NOR2X2 U32 (.IN1 ( n42 ) , .QN ( n41 ) , .IN2 ( G1 ) ) ;
INVX2 U34 (.QN ( n42 ) , .IN ( G3 ) ) ;
NOR2X2 U35 (.IN1 ( Scan_Out ) , .QN ( net9 ) , .IN2 ( G1 ) ) ;
INVX2 U37 (.IN ( n2 ) , .QN ( net371 ) ) ;
OA21X2 U39 (.Q ( n27 ) , .IN2 ( n1 ) , .IN3 ( G0 ) , .IN1 ( net371 ) ) ;
INVX2 U41 (.QN ( net416 ) , .IN ( G17 ) ) ;
NOR2X2 U42 (.IN1 ( net9 ) , .QN ( G13 ) , .IN2 ( G2 ) ) ;
INVX2 U43 (.IN ( blif_reset_net ) , .QN ( n33 ) ) ;
endmodule


